/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditBinderRouteImport } from './routes/audit-binder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as ScanTransferRouteImport } from './routes/scan-transfer'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditBinderRoute = AuditBinderRouteImport.update({
  id: '/audit-binder',
  path: '/audit-binder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanTransferRoute = ScanTransferRouteImport.update({
  id: '/scan-transfer',
  path: '/scan-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-binder': typeof AuditBinderRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/personnel': typeof PersonnelRoute
  '/scan-transfer': typeof ScanTransferRoute
  '/super-admin': typeof SuperAdminRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-binder': typeof AuditBinderRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/personnel': typeof PersonnelRoute
  '/scan-transfer': typeof ScanTransferRoute
  '/super-admin': typeof SuperAdminRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-binder': typeof AuditBinderRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/personnel': typeof PersonnelRoute
  '/scan-transfer': typeof ScanTransferRoute
  '/super-admin': typeof SuperAdminRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-binder'
    | '/auth'
    | '/import'
    | '/personnel'
    | '/scan-transfer'
    | '/super-admin'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-binder'
    | '/auth'
    | '/import'
    | '/personnel'
    | '/scan-transfer'
    | '/super-admin'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/audit-binder'
    | '/auth'
    | '/import'
    | '/personnel'
    | '/scan-transfer'
    | '/super-admin'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditBinderRoute: typeof AuditBinderRoute
  AuthRoute: typeof AuthRoute
  ImportRoute: typeof ImportRoute
  PersonnelRoute: typeof PersonnelRoute
  ScanTransferRoute: typeof ScanTransferRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-binder': {
      id: '/audit-binder'
      path: '/audit-binder'
      fullPath: '/audit-binder'
      preLoaderRoute: typeof AuditBinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-transfer': {
      id: '/scan-transfer'
      path: '/scan-transfer'
      fullPath: '/scan-transfer'
      preLoaderRoute: typeof ScanTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditBinderRoute: AuditBinderRoute,
  AuthRoute: AuthRoute,
  ImportRoute: ImportRoute,
  PersonnelRoute: PersonnelRoute,
  ScanTransferRoute: ScanTransferRoute,
  SuperAdminRoute: SuperAdminRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
